### ISSUE TITLE
ADD convert price to EUR USD whatever configured

### ISSUE THREAD

**Issue by allanlaal** [subz390/ebaytotalprice-userscript#1]
inspiration:
https://userscripts-mirror.org/scripts/review/68442

**Comment by subz390** [comment]
That's interesting, how would you use the feature?
Do you mean the total price in what ever currency you choose?

**Comment by allanlaal** [comment]
yes, the total price in EUR is what I'm looking for
I shop a lot on different ebay sites

i.e. Poland is in the EU, but they are not using EUR - although its often the closest country to ship from :)

**Comment by subz390** [comment]
OK I'll schedule some time to investigate the best way to implement this.
I'm currently busy on another project so it may take a week or two before I can free up time to work on this.
I'll update the progress in this thread.

**Comment by subz390** [comment]
I've carried out my investigation and taken time to consider this feature and I it's not something that I would use myself.  Whilst I can see the benefit of currency conversion I feel that it's beyond the scope of this particular userscript.  If someone else were to develop a script that does currency conversion I'd be happy to add a particular `data` type to the HTML element of this script so they can add an eventListener to capture and then modify it.
